### ISSUE TITLE
Some confuses about ranknet

### ISSUE THREAD

**Issue by Sean0719** [airalcorn2/RankNet#2]
Hi,

Sorry to disturb you. For me I have confused about the weight that the network learned. This means that for each query [q1,q2,...qn] with documents[d1,d2....dm] the network will learn the w1i[w11,w12....] for the query1 and w2i[w21,w22....] for the query2? Could you please give me some helps. Thank you very much.

Sean

**Comment by airalcorn2** [comment]
Sorry, I do not understand your question.

**Comment by Sean0719** [comment]
I mean that when do training, you will train different weight for the different query or all queries share the same weight. Thanks.

**Comment by airalcorn2** [comment]
The model learns one set of weights.
