### ISSUE TITLE
How to input the query into Ranknet?

### ISSUE THREAD

**Issue by george-pch806771** [airalcorn2/RankNet#8]
Hi,
The model structure of Ranknet shows that it just use the feature of document as input,
Does Ranknet use query as input too?How?

**Comment by airalcorn2** [comment]
The input features to RankNet include "query-dependent" features. See Section 6.1 in "[Learning to Rank using Gradient Descent](https://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)".
